name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4.4"
    - uses: leafo/gh-actions-luarocks@v4
    - name: setup 
      run: |
        luarocks install luaunit 3.4-1
        luarocks install lpeg 1.0.2-1
        
    - name: test
      run: |
        ./ena.lua --tests
